# Generated by Django 5.0.6 on 2024-07-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_follower_follower'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
